import test from 'node:test';
import assert from 'node:assert/strict';
import {cosineSimilarity, appendSemanticResults, MODEL} from '../public/modules/semantic-ai.mjs';
test('cosine arithmetic', () => { assert.equal(cosineSimilarity([1,0],[1,0]),1); assert.equal(cosineSimilarity([1,0],[0,1]),0); assert.equal(cosineSimilarity([1,0],[-1,0]),-1); });
test('mismatched dimensions rejected', () => assert.throws(() => cosineSimilarity([1],[1,2])));
const actualExecution = {actualInference:true, completed:true};
const report = () => ({rows:[{key:'r1',rowNumber:1,verseId:'1:1',status:'needs_review',translation:'candidate',reference:{translation:'reference',provenance:{url:'https://example.org'}},comparisonStatus:'compared',findings:[{id:'n',code:'potential_negation_change',type:'comparison'}],findingIds:['n']}],findings:[{id:'n',code:'potential_negation_change',type:'comparison'}],summary:{},provenance:{analysis:{limitations:[]}}});
test('high neural similarity never removes negation or approves', () => { const original = report(); const out = appendSemanticResults(original,[{key:'r1',similarity:.98}],actualExecution); assert.equal(out.rows[0].status,'needs_review'); assert.equal(original.rows[0].semantic,undefined); assert.equal(out.rows[0].semantic.scoreIsAccuracy,false); });
test('low distance adds review not religious judgment', () => { const out = appendSemanticResults(report(),[{key:'r1',similarity:.2}],actualExecution); assert.equal(out.findings.length,2); assert.equal(out.findings[1].evidence.calibrated,false); assert.equal(out.provenance.analysis.trainedModelExecuted,true); });
test('long inputs disclose truncation even when similarity high', () => { const out = appendSemanticResults(report(),[{key:'r1',similarity:.99,candidateTruncated:true}],actualExecution); assert.equal(out.findings[1].code,'semantic_input_truncated'); });
test('pinned model revision, license and limits', () => { assert.match(MODEL.revision,/^[a-f0-9]{40}$/); assert.equal(MODEL.license,'MIT'); assert.equal(MODEL.maxTokens,512); });
test('abstained reference cannot be upgraded by forged supplied model result', () => { const original = report(); original.rows[0].comparisonStatus='abstain'; const out=appendSemanticResults(original,[{key:'r1',similarity:.5}],actualExecution); assert.equal(out.provenance.analysis.trainedModelExecuted,false); assert.equal(out.rows[0].semantic,undefined); });
test('invalid and duplicated scores cannot inflate model coverage', () => { const out=appendSemanticResults(report(),[{key:'r1',similarity:2},{key:'r1',similarity:.9},{key:'r1',similarity:.8}],actualExecution); assert.equal(out.summary.semanticProcessedRows,1); });

test('supplied scores without explicit actual inference never claim a model ran', () => { for (const execution of [{},{actualInference:false}]) { const out=appendSemanticResults(report(),[{key:'r1',similarity:.2}],execution); assert.equal(out.provenance.analysis.trainedModelExecuted,false); assert.equal(out.summary.semanticProcessedRows,0); assert.equal(out.rows[0].semantic,undefined); } });
test('identical strings are not eligible for fabricated semantic coverage', () => { const input=report(); input.rows[0].translation=input.rows[0].reference.translation; const out=appendSemanticResults(input,[{key:'r1',similarity:.2}],actualExecution); assert.equal(out.summary.semanticEligibleRows,0); assert.equal(out.summary.semanticProcessedRows,0); });
